// AUTO-GENERATED by SdkExport KSP processor — DO NOT EDIT

export interface CommonApiResponse<T> {
  status: string;
  code: number;
  message: string;
  data: T;
}

export type ClubType = 'MAJOR_CLUB' | 'AUTONOMOUS_CLUB';

export interface ClubMemberDto {
  studentId: number;
  joinedAt: string;
}

export interface ClubResDto {
  id: number;
  name: string;
  type: ClubType;
  members: ClubMemberDto[];
  tags: (string | null)[];
  meta: Record<string, number>;
  description?: string;
}

export interface PageResDto<T> {
  content: T[];
  total: number;
}
