services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=datagsm'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=secret'
      - 'MYSQL_USER=datagsm'
    ports:
      - '3306:3306'
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
