services:
  datagsm-web:
    build:
      context: ./datagsm-web
      dockerfile: prod.dockerfile
    container_name: datagsm-web-prod
    ports:
      - "8080:8080"
    restart: unless-stopped

  datagsm-authorization:
    build:
      context: ./datagsm-authorization
      dockerfile: prod.dockerfile
    container_name: datagsm-auth-prod
    ports:
      - "8081:8081"
    restart: unless-stopped

  datagsm-resource:
    build:
      context: ./datagsm-resource
      dockerfile: prod.dockerfile
    container_name: datagsm-resource-prod
    ports:
      - "8082:8082"
    restart: unless-stopped
