package team.themoment.datagsm.ksp.processor

// Plain, KSP-free model and renderer for the generated index.d.ts.
// Kept separate from KmpExportProcessor so the rendering and validation logic can be
// unit-tested against golden files without a full KSP compilation round.

internal data class TsEnum(
    val name: String,
    val members: List<String>,
)

internal data class TsProperty(
    // The emitted property key (the @field:JsonProperty serial name).
    val name: String,
    val type: String,
    val optional: Boolean,
    // Custom (non-builtin) type names this property references. Used by validate() to
    // confirm every referenced DTO/enum is itself exported.
    val references: Set<String> = emptySet(),
)

internal data class TsInterface(
    val name: String,
    val typeParameters: List<String>,
    val properties: List<TsProperty>,
)

internal data class TsModel(
    val enums: List<TsEnum>,
    val interfaces: List<TsInterface>,
)

internal object TsDefinitionEmitter {
    // Hardcoded preamble type; referencing it from a DTO is always allowed.
    private const val COMMON_API_RESPONSE = "CommonApiResponse"

    // Returns a list of human-readable errors; an empty list means the model is emittable.
    // Catches the two failure modes the silent simpleName fallback used to hide:
    // duplicate flattened names, and references to types that were never @KmpExport-ed.
    fun validate(model: TsModel): List<String> {
        val errors = mutableListOf<String>()

        val allNames = model.enums.map { it.name } + model.interfaces.map { it.name }
        val duplicates =
            allNames
                .groupingBy { it }
                .eachCount()
                .filterValues { it > 1 }
                .keys
        if (duplicates.isNotEmpty()) {
            errors += "Duplicate type names after flattening ${duplicates.sorted().joinToString(", ")}"
        }

        val exported = (allNames + COMMON_API_RESPONSE).toSet()
        model.interfaces.forEach { iface ->
            val visible = exported + iface.typeParameters
            iface.properties.forEach { prop ->
                (prop.references - visible).sorted().forEach { missing ->
                    errors +=
                        "Type '$missing' referenced by ${iface.name}.${prop.name} is not exported (missing @KmpExport?)"
                }
            }
        }
        return errors
    }

    // Emits a single flat index.d.ts: CommonApiResponse<T> preamble, enums as string-literal
    // unions, and DTOs as interfaces. Types are sorted by name for deterministic output.
    // Lines are joined with explicit '\n' (not appendLine) so output is identical regardless
    // of the host OS line separator — the published .d.ts must be byte-stable across CI.
    fun render(model: TsModel): String {
        val lines = mutableListOf<String>()
        lines += "// AUTO-GENERATED by KmpExport KSP processor — DO NOT EDIT"
        lines += ""
        lines += "export interface CommonApiResponse<T> {"
        lines += "  status: string;"
        lines += "  code: number;"
        lines += "  message: string;"
        lines += "  data: T;"
        lines += "}"
        lines += ""

        model.enums
            .sortedBy { it.name }
            .forEach { e ->
                val union = e.members.joinToString(" | ") { "'$it'" }
                lines += "export type ${e.name} = $union;"
            }
        if (model.enums.isNotEmpty()) lines += ""

        model.interfaces
            .sortedBy { it.name }
            .forEach { iface ->
                val typeParams =
                    if (iface.typeParameters.isNotEmpty()) "<${iface.typeParameters.joinToString(", ")}>" else ""
                lines += "export interface ${iface.name}$typeParams {"
                iface.properties.forEach { prop ->
                    val optional = if (prop.optional) "?" else ""
                    lines += "  ${prop.name}$optional: ${prop.type};"
                }
                lines += "}"
                lines += ""
            }

        return lines.joinToString("\n").trimEnd() + "\n"
    }
}
