spring:
  application:
    name: datagsm-oauth-userinfo
  docker:
    compose:
      enabled: true
      file: compose.local.yaml
      lifecycle-management: start_and_stop
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/datagsm?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Seoul}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      database: 0
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        default_batch_fetch_size: 100
  cloud:
    discord:
      webhook:
        url: ${DISCORD_EMERGENCY_ALERT_CHANNEL_WEBHOOK}
  security:
    cors:
      allowed-origins:
        - ${CORS_ALLOWED_ORIGINS:*}
    oauth-jwt:
      public-key: ${JWT_PUBLIC_KEY}
  web:
    error:
      whitelabel:
        enabled: false
      include-message: always
      include-binding-errors: always
      include-stacktrace: never
      include-exception: false
server:
  port: 8083
  shutdown: graceful
sdk:
  logging:
    enabled: true
    not-logging-urls:
      - "/v3/api-docs/**"
      - "/swagger-ui/**"
  response:
    enabled: true
    not-wrapping-urls:
      - "/v3/api-docs/**"
      - "/swagger-ui/**"
  swagger:
    enabled: true
    title: "DataGSM OAuth Userinfo Server API"
    description: "OAuth 2.0 Userinfo Server"
    version: "v1"
    group: "oauth-userinfo-api"
    paths-to-match:
      - "/userinfo"
  exception:
    enabled: false
    use-english-message: false
springdoc:
  swagger-ui:
    enabled: true
logging:
  config: classpath:logback-spring.xml
